### ISSUE TITLE
Replace DW1820a NIC and add related kext fails to boot

### ISSUE THREAD

**Issue by Luke9570** [Baio1977/Lenovo-V130-15IKB-Kabylake#1]
Hi, I used this EFI and found that the AC 3165 airdrop does not work properly, I replaced the Broadcom DW1820a NIC and added AirportBrcmFixup (removed AirPortBrcm4360) and BrcmPatchRAM, now it does not boot properly, this seems to be the problem of the added kext, how can I change the efi to make the hackintosh boot properly?
![1](https://user-images.githubusercontent.com/82377331/139283855-432b7add-82e6-4fe7-a223-a70ffe251c20.jpg)

**Comment by Baio1977** [comment]
Test this ioreg if start
[EFI.zip](https://github.com/Baio1977/Lenovo-V130-15IKB-Kabylake/files/7437054/EFI.zip)

you have 2 Kext different version in config
![Schermata 2021-10-28 alle 22 09 49](https://user-images.githubusercontent.com/59058746/139328552-69e305a4-ac83-499d-b4c0-ee0cb192507e.png)

**Comment by Luke9570** [comment]
This EFI DW1820a‘s wifi and Bluetooth functions are working properly, thank you
